---
sidebar: sidebar
permalink: concept-cvs-gcp.html
keywords: cloud volumes service for gcp, google cloud, cloud volumes, cloud volumes service subscription
summary: NetApp Cloud Volumes Service for Google Cloud enables you to quickly add multi-protocol workloads as well as build and deploy both Windows-based and UNIX-based apps.
---

= Learn about Cloud Volumes Service for Google Cloud
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
NetApp Cloud Volumes Service for Google Cloud enables you to quickly add multi-protocol workloads as well as build and deploy both Windows-based and UNIX-based apps.

== Key features

* Migrate data between on-premises and Google Cloud.

* Provision volumes from 1 to 100 TiB in seconds.

* Multiprotocol support (you can create an NFS or SMB volume).

* Protect data with automated, efficient snapshots.

* Accelerate app development with rapid cloning.

== Cost

Volumes created by the Cloud Volumes Service for Google Cloud are charged to your subscription to the service, not through Cloud Manager.

There are no charges to discover a Cloud Volumes Service for Google Cloud region or volume from Cloud Manager.

link:https://console.cloud.google.com/marketplace/product/endpoints/cloudvolumesgcp-api.netapp.com?q=cloud%20volumes%20service[View pricing in the Google Cloud Marketplace^]

== Supported regions

link:https://cloud.google.com/solutions/partners/netapp-cloud-volumes/regional-availability[View supported Google Cloud regions^]

== Before you get started

Cloud Manager can discover existing Cloud Volumes Service for GCP subscriptions and volumes. See the https://cloud.google.com/solutions/partners/netapp-cloud-volumes/[NetApp Cloud Volumes Service for Google Cloud documentation^] if you haven't set up your subscription yet.

== Getting help

Use the Cloud Manager chat for general questions about Cloud Volumes Service operation in Cloud Manager.

For general questions about Cloud Volumes Service for Google Cloud, email NetApp’s Google Cloud Team at gcinfo@netapp.com.

For technical issues associated with your cloud volumes, you can create a technical support case from the Google Cloud Console. See link:https://cloud.google.com/solutions/partners/netapp-cloud-volumes/support[obtaining support^] for details.

== Related links

* https://cloud.netapp.com/cloud-volumes-service-for-gcp[NetApp Cloud Central: Cloud Volumes Service for Google Cloud^]
* https://cloud.google.com/solutions/partners/netapp-cloud-volumes/[NetApp Cloud Volumes Service for Google Cloud documentation^]
