settings:
  name: Cloud Volumes Service for Google Cloud
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
sidebar:
  entries:
    - title: Cloud Volumes Service for Google Cloud docs
      url: /index.html
    - title: Release notes
      url: /whats-new.html
    - title: Get started
      entries:
        - title: Learn about Cloud Volumes Service for Google Cloud
          url: /concept-cvs-gcp.html
        - title: Quick start
          url: /task-quick-start.html
        - title: Set up Google Cloud
          url: /task-set-up-google-cloud.html
        - title: Create a working environment
          url: /task-create-working-env.html
    - title: Use Cloud Volumes Service for Google Cloud
      entries:
        - title: Create and mount volumes
          url: /task-create-volumes.html
        - title: Manage existing volumes
          url: /task-manage-volumes.html
        - title: Manage cloud volumes snapshots
          url: /task-manage-snapshots.html
        - title: Manage your Active Directory configuration
          url: /task-manage-active-directory.html
        - title: Remove Cloud Volumes Service
          url: /task-remove-working-env.html
    - title: Knowledge and support
      entries:
        - title: Register for support
          url: /task-support-registration.html
        - title: Get help
          url: /task-get-help.html
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: Cloud Manager
  repo: cloud-manager-family
  sidebar_label: All Cloud Manager documentation
homepage:
  tiles:
    - title: Get started
      links:
        - title: Learn about Cloud Volumes Service for Google Cloud
          url: concept-cvs-gcp.html
        - title: Quick start
          url: task-quick-start.html
    - title: Use Cloud Volumes Service
      links:
        - title: Create volumes
          url: task-create-volumes.html
        - title: Manage cloud volumes snapshots
          url: task-manage-snapshots.html
    - title: Blogs & community
      links:
        - title: NetApp Community
          url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
        - title: Cloud Central blog
          url: https://cloud.netapp.com/blog
        - title: Cloud webinars
          url: https://cloud.netapp.com/events
