---
sidebar: sidebar
permalink: task-set-up-google-cloud.html
keywords: setup, set up, api, service account, requirements, permissions
summary: Cloud Manager needs access to the Cloud Volumes Service API and the right permissions through a Google Cloud service account.
---

= Set up Google Cloud
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Cloud Manager needs access to the Cloud Volumes Service API and the right permissions through a Google Cloud service account.

== Enable the Cloud Volumes Service API

In Google Cloud Shell, run the following command to enable the Cloud Volumes Service API:

`gcloud --project=<my-cvs-project> services enable cloudvolumesgcp-api.netapp.com`

== Set up a service account

Complete the following tasks so that Cloud Manager can access your Google Cloud project:

* Create a new service account
* Add the new service account member to your project and assign it specific roles (permissions)
* Create and download a key pair for the service account that is used to authenticate to Google

.Steps

. In the Google Cloud console, https://console.cloud.google.com/iam-admin/serviceaccounts[go to the Service accounts page^].

. Click *Select a project*, choose your project, and click *Open*.

. Click *Create service account*.

. Enter the service account name (friendly display name) and description.
+
The Cloud Console generates a service account ID based on this name. Edit the ID if necessary - you cannot change the ID later.

. To set access controls now, click *Create* and then *DONE* from the bottom of the page, and continue to the next step.

. From the _IAM page_ click *Add* and fill out the fields in the _Add Members_ page:
.. In the New Members field, enter the full service account ID, for example, user1-service-account-cvs@project1.iam.gserviceaccount.com.
.. Add these roles:
* _NetApp Cloud Volumes Admin_
* _Compute Network Viewer_
.. Click *Save*.

. Click the Service Account name, and then from the _Service account details_ page, click *Add key > Create new key*.

. Select *JSON* as the key type and click *Create*.
+
By clicking *Create* your new public/private key pair is generated and downloaded to your system. It serves as the only copy of the private key. Store this file securely because it can be used to authenticate as your service account.

For detailed steps, refer to Google Cloud documentation:

* link:https://cloud.google.com/iam/docs/creating-managing-service-accounts[Creating and managing service accounts^]
* link:https://cloud.google.com/iam/docs/granting-changing-revoking-access[Granting, changing, and revoking access to resources^]
* link:https://cloud.google.com/iam/docs/creating-managing-service-account-keys[Creating and managing service account keys^]
